smtp_server: "smtp.gmail.com"
smtp_port: 587
send_mail: olegrakovic323@gmail.com
send_mail_password: yfyxtgwaiajllaia


recovery_mail: olegrakovic323@gmail.com

minimal_password_length: 5
banned_passwords:
  - "12345"
  - "1234567890"
  - "qwerty"

minimal_username_length: 1
banned_usernames:
  -