smtp_server: "smtp.gmail.com"
smtp_port: 587
send_mail:
send_mail_password:

recovery_mail:

database_name: vacations
database_user: postgres
database_password: root

minimal_password_length: 5
banned_passwords:
  - "12345"
  - "1234567890"
  - "qwerty"

minimal_username_length: 1
banned_usernames:
  -